version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: django_postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c max_connections=150
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
